#@server =  https://miguelangel2022sistemas-refactored-x7g54vr6vpj2p5v5-8080.preview.app.github.dev


@server = https://s8miguel.onrender.com
###
GET {{server}}
###
GET {{server}}/cursos

###Agregar
POST  {{server}}/cursos
Content-Type: application/json

{"nombre": "comunicacion", "creditos":3}

###ver por id
GET {{server}}/cursos/3
###editar
PATCH   {{server}}/cursos/2
Content-Type: application/json

{"nombre": "quimica"}

###ver por orden
GET {{server}}/cursos?size=2&page=0

###ver por orden
GET {{server}}/cursos?size=2&page=0&sort=creditos,desc

###ver por orden
GET {{server}}/cursos?size=2&page=1&sort=creditos,desc

###ver 
GET {{server}}/cursos/search/findByNombre?nombre=quimica

########################################################

###
GET {{server}}/carreras

###Agregar
POST  {{server}}/carreras
Content-Type: application/json

{"nombre": "Desarrollo de sistemas e informacion"}

###Agregar
POST  {{server}}/carreras
Content-Type: application/json

{"nombre": "Marketing"}


###
GET {{server}}/carreras/2

###
GET {{server}}/carreras/1/cursos

###
GET {{server}}/cursos/1/carrera


